[package]
name = "vexdoc"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.12"
serde = { version = "1.0.204", features = ["derive"] }
toml = "0.8.14"
build_html = "2.5.0"

[dev-dependencies]
assert_cmd = "2.0.14"
assert_fs = "1.1.1"
predicates = "3.1.0"
rand = "0.8.4"
