name: Release

on:
  push:
    tags: "v*.*.*"

permissions:
  contents: write

jobs:
  build_and_release:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Move binaries linux
        run: mv target/release/vexdoc .
        if: ${{ matrix.os }} == "ubuntu-*"
      - name: Move binaries windows
        run: move target\\release\\vexdoc.exe .
        if: ${{ matrix.os }} == "windows-*"
      - if: endswith(${{ github.ref}}, "tags/v*-rc*")
        name: prerelease
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          files: |
            vexdoc
            vexdoc.exe
      - if: '!endswith(${{ github.ref}}, "tags/v*-rc*")'
        name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          files: |
            vexdoc
            vexdoc.exe
